on: [push, pull_request]

name: CI

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo build
      - run: cargo test
